apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-test-chart-configmap
data:
  index.html: |
    <html>
    <body>
    <h1>{{ .Values.greeting }}</h1>
    <h2>A Really Very important message from our sponsor {{.Values.sponsor}} </h2>
    <h3>{{.Values.message}}</h3>
    </body>
    </html>
