apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: argo-test-chart-nginx-rollout
  labels:
    app: nginx
spec:
  replicas: 2
  strategy:
    canary:
      steps:
        - setWeight: 50
          pause: {duration: 10}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
          - containerPort: 80
          volumeMounts:
            - name: argo-test-chart-configmap-volume
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: argo-test-chart-configmap-volume
          configMap:
            name: argo-test-chart-configmap
