apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  namespace: argo-workflows
  generateName: post-sync-
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  entrypoint: alpine-hello
  templates:
    - name: alpine-hello
      container:
        image: ghcr.io/iamdo/test-image:0.1.0
        command: [echo]
        args: ["Hello, World from hook!"]

