apiVersion: v1
kind: Deployment
metadata:
  name: argo-test-chart-nginx-rollout
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/argo-test-chart-configmap.yaml") . | sha256sum }}
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
          - containerPort: 80
          volumeMounts:
            - name: argo-test-chart-configmap-volume
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: argo-test-chart-configmap-volume
          configMap:
            name: argo-test-chart-configmap
